Tkl/dev/layout
IONOS-Productivity/nc-theming pull request #29
Opened 2024-12-19 20:21 UTC by tanyaka

2025-01-02 08:45 UTC, fracado requested changes
There seems to be no need for a --list-row-height variable. Simply changing the --row-height variable seems to work fine.

Adjustment for breadcrumb on mobile is missing.

Also, the positioning of the icon for the table header for "size" needs to be adjusted.

See review branch: https://github.com/IONOS-Productivity/nc-theming/compare/tkl/dev/layout...fb/review/layout

Changes in PR https://github.com/IONOS-Productivity/nc-server/pull/78 don't seem to be needed and commits (apart from the submodule update) can be dropped.

2025-01-06 12:59 UTC, tanyaka commented
> There seems to be no need for a --list-row-height variable. Simply changing the --row-height variable seems to work fine.
> 
> Adjustment for breadcrumb on mobile is missing.
> 
> Also, the positioning of the icon for the table header for "size" needs to be adjusted.
> 
> See review branch: [tkl/dev/layout...fb/review/layout](https://github.com/IONOS-Productivity/nc-theming/compare/tkl/dev/layout...fb/review/layout)
> 
> Changes in PR [IONOS-Productivity/nc-server#78](https://github.com/IONOS-Productivity/nc-server/pull/78) don't seem to be needed and commits (apart from the submodule update) can be dropped.

@fracado , thank you so much for your feedback and suggestions,  I like them very much!
Concerning the "the positioning of the icon for the table header for "size"" according to design template, the "size" row is not aligned with the header, as well as the folder size in the footer. added alignment with f21f96dd1377fe2feb25f617b8c30b55bd638299

2025-01-06 13:32 UTC, tanyaka commented
Added fix for thumbnail size for grid view: [1e6fc7c](https://github.com/IONOS-Productivity/nc-theming/pull/29/commits/1e6fc7cf89055705bc2d746c6384511b3ad8050e): since the update to NC version 30 the thumbnails in grid view were too large. That was already fixed for new FA icons in apps/files, but probably was lost while update-rebase. So fixed it here.

2025-01-07 11:07 UTC, fracado approved these changes
Review OK

2025-01-09 09:53 UTC, merged